import { FeedPostItem } from "./posts";

export const mockPosts: FeedPostItem[] = [
  {
    id: "1",
    author: {
      name: "Dona Fofoca (Bairro do Limoeiro)",
      username: "dona_fofoca_oficial",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOKeTnnRBp-zxVdRJedDqDVxVyPc0pJVAv0Q&s",
    },
    content: "🚨 BOMBA NO BAIRRO: O FIM DO MISTÉRIO DO CASCÃO!\n\nApós décadas evitando qualquer contato com a água, o Cascão finalmente abriu o jogo em uma live exclusiva. Segundo o jovem, tudo começou com uma promessa feita em 1963 para que o Bairro do Limoeiro nunca sofresse com secas extremas. 'Eu fiz um pacto com as nuvens, se eu ficasse sujo, a chuva sempre viria para as plantações da Dona Cebola', revelou emocionado.\n\nPorém, a fofoca não para por aí: fontes próximas afirmam que ele foi flagrado comprando um shampoo a seco caríssimo em um shopping de elite. Seria esse o fim da era 'sujinho'? O Cebolinha comentou na publicação com um 'pola, finalmente', mas apagou logo em seguida. A assessoria do personagem ainda não confirmou se o banho oficial acontecerá no próximo verão.",
    image: "https://www.estadao.com.br/resizer/OP2eXjYEDwEw3z7dGxgvStXGvmQ=/arc-anglerfish-arc2-prod-estadao/public/NNK3F3DSAFFUVMVXDJN76EX2YI.jpg", 
    createdAt: new Date("2026-04-01T10:00:00Z"),
    likes: 15420,
    comments: 892,
  },
  {
    id: "2",
    author: {
      name: "Gazeta da Fenda",
      username: "gazeta_fenda",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwzggd6atLthcx293FkT_0d46GItnjLRdGXA&s",
    },
    content: "🐙 LULA MOLUSCO É PEGO NO PULO!\n\nQuem vê a cara de tédio no caixa do Siri Cascudo não imagina o que acontece nas madrugadas da Fenda do Biquíni. O clarinetista foi flagrado em um buffet livre de Hambúrguer de Siri devorando nada menos que 42 sanduíches em 10 minutos. \n\nTestemunhas afirmam que ele chorava de alegria e gritava que 'o Bob Esponja é um gênio incompreendido'. Quando percebeu que estava sendo filmado, Lula Molusco recuperou a postura, chamou todos de 'plebeus sem cultura' e saiu sem pagar a conta. Rumores indicam que ele está tentando uma vaga no MasterChef Marítimo e todo aquele mau humor é apenas um personagem para não ser incomodado por fãs.",
    image: "https://i.pinimg.com/564x/70/07/78/700778995e98ebc867b0dc00bf6acce0.jpg",
    createdAt: new Date("2026-03-31T09:00:00Z"),
    likes: 9800,
    comments: 415,
  },
  {
    id: "3",
    author: {
      name: "Gotham Gazette",
      username: "gotham_gazette",
      avatar: "https://i.pinimg.com/736x/3e/00/b7/3e00b786a1123460f5b659a9963c6f29.jpg",
    },
    content: "🦇 CRISE NAS INDÚSTRIAS WAYNE? \n\nA vida de bilionário não está fácil para ninguém. Bruce Wayne foi visto circulando por Gotham com um adesivo de 'Uber Black' no novo Batmóvel. Um passageiro sortudo (ou aterrorizado) relatou que solicitou uma viagem e foi atendido por um homem de máscara que se recusou a falar o nome, apenas rosnava: 'Eu sou a justiça (e a sua corrida deu 15 reais)'.\n\nEspecialistas financeiros dizem que os gastos com bat-shurikens e consertos de capas de kevlar estouraram o orçamento anual da fundação. Se você pedir um carro hoje em Gotham, pode ser que chegue em um tanque de guerra preto fosco!",
    image: "https://www.pedestrian.tv/wp-content/uploads/2024/09/uber-batmobile-sydney-adelaide.png?quality=50",
    createdAt: new Date("2026-03-30T14:30:00Z"),
    likes: 28900,
    comments: 1430,
    isLiked: true,
  },
  {
    id: "4",
    author: {
      name: "PokéJornal (Kanto)",
      username: "pokejornal_news",
      avatar: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=100&h=100&fit=crop",
    },
    content: "⚡ O SEGREDO DA JUVENTUDE ETERNA DE ASH KETCHUM!\n\nVocê já se perguntou como um garoto de 10 anos consegue ter a mesma idade desde 1997? O PokéJornal investigou e descobriu a rotina bizarra de Ash. Além de uma dieta rigorosa baseada em Frutas Berries colhidas no sereno, o treinador de Pallet usa um creme facial feito com extrato de Celebi e escamas de Gyarados.\n\n'O segredo é nunca ganhar uma liga mundial de primeira, o estresse de ser campeão envelhece as pessoas', disse Ash em entrevista exclusiva. Além disso, fontes dizem que ele dorme dentro de uma Pokébola térmica que preserva as células. Será que o tempo realmente para quando você tem um rato elétrico no ombro?",
    image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjf0Bx4vSbev4-VcgfdkxErdDynTKSZuVorXf9_NZLooCD-fMSJ_56bOx4on9xRTj4GkwuQEjjo4mQ47tbw8IfxDzoLtkTnaUfokaLz5jtZZ3xs0anHFWQn5whA2DGdJzg0_S8tiGlCfM_2/s1600/5abb325238114d00997c422111882a69319b6a7f.jpg__576x480_q85.jpg",
    createdAt: new Date("2026-03-29T11:20:00Z"),
    likes: 18200,
    comments: 650,
  },
  {
    id: "5",
    author: {
      name: "The Daily Bugle (Clarim Diário)",
      username: "daily_bugle_official",
      avatar: "https://i.scdn.co/image/ab6765630000ba8a271bc0476761762f46a766af",
    },
    content: "🕸️ A FARSA ACABOU! HOMEM-ARANHA ODEIA ARANHAS? \n\nEU SEMPRE AVISEI! O suposto 'herói' de Nova York foi flagrado fugindo de suas próprias responsabilidades. Recebemos fotos exclusivas dessa ameaça mascarada comprando ESTOQUES de inseticida ultra-forte em um mercado de quinta categoria. Estaria o 'Escalador de Paredes' tentando exterminar sua própria espécie para manter o monopólio das teias na cidade?\n\nEm uma tentativa pífia de se explicar para nossa reportagem enquanto fugia covardemente, o mascarado declarou: 'Gente, não é o que vocês estão pensando! Minha cozinha foi invadida por umas primas distantes de oito patas que não pagam aluguel e eu não vou usar meus poderes contra civis indefesos, né?'.\n\nCivis indefesos, Parker? Ou seriam seus cúmplices? A verdade é que o Homem-Aranha é uma fraude! Se ele não consegue nem lidar com as aranhas da própria casa, como pode proteger nossa cidade? #SpiderFraude #JamesonEstavaCerto",
    image: "https://cinemacao.com/wp-content/uploads/2019/07/longe-de-casa-homem-aranha-3-1130x590.jpg",
    createdAt: new Date("2026-03-28T08:15:00Z"),
    likes: 95400,
    comments: 12500,
    isSaved: true,
  },
  {
    id: "6",
    author: {
      name: "O Patópolis Diário",
      username: "duckburg_daily",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_N_X-fP6q1D6v6Fm1kFfP8fE8O7zG2D3w4A&s",
    },
    content: "🦆 ESCÂNDALO NA CAIXA FORTE: MOEDA Nº 1 É FALSA?\n\nO império de Patópolis está tremendo! Uma perícia técnica realizada secretamente pelo Prof. Pardal revelou que a famosa 'Moeda Número 1' do Tio Patinhas é, na verdade, um chocolate suíço banhado a ouro que venceu em 1954. \n\nDonald, em estado de choque, declarou: 'Eu sempre achei estranho o cheiro de baunilha quando ele me mostrava o cofre'. Patinhas se recusou a dar entrevista, mas foi visto correndo atrás do perito com uma bengala enquanto gritava sobre 'impostos e conspirações'. #DuckLeaks #ChocolateAmargo",
    image: "https://www.blogderocha.com.br/wp-content/uploads/2019/04/18033565_10203004724196642_3609915426002633993_n.jpg",
    createdAt: new Date("2026-03-27T16:45:00Z"),
    likes: 42300,
    comments: 2100,
  },
  {
    id: "7",
    author: {
      name: "Rádio Vila do Chaves", 
      username: "radio_vila",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_xNqXq_D_j1_1D_j1_1D_j1_1D_j1_1D_j1_1D_j1_1D_j1_1",
    },
    content: "☕ EXCLUSIVO: O CAFÉ ERA CILADA? \n\nApós anos aceitando convites para 'tomar uma xícara de café', o Professor Girafales foi flagrado saindo de uma cafeteria gourmet com nada menos que a Dona Clotilde, a Bruxa do 71. \n\nO flagra aconteceu no centro da cidade. Testemunhas dizem que o Professor não carregava flores, mas sim um buquê de coentro. 'Não é o que parece, eu estava apenas dando aulas particulares de botânica', afirmou o mestre. Dona Florinda foi vista batendo a porta com força. O clima na vila nunca esteve tão pesado! #CafeTraicao #VilaEmChamas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_cfzpVywaVRIAd-eJlwYP-9itzUrpVONE6A&s",
    createdAt: new Date("2026-03-26T20:10:00Z"),
    likes: 12900,
    comments: 850,
  },
  {
    id: "8",
    author: {
      name: "The Daily Planet",
      username: "daily_planet_metropolis",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6-m6m",
    },
    content: "👓 O MISTÉRIO DOS ÓCULOS: CLARK KENT É MÍOPE OU APENAS ESTILOSO?\n\nUma investigação profunda revelou que Clark Kent, o repórter estrela do Planeta Diário, usa lentes sem grau desde que entrou na empresa. Por que um homem saudável precisaria de um disfarce tão óbvio? \n\nLois Lane comentou rindo: 'Às vezes ele tira os óculos e eu juro que ele fica a cara do Superman, mas aí ele tropeça em um arquivo e eu desisto da ideia'. Seria essa a maior estratégia de marketing da história do jornalismo ou ele só quer esconder olheiras de quem voa a noite toda? #ClarkLook #FakeGlasses",
    image: "https://preview.redd.it/in-the-1978-superman-the-movie-and-its-sequels-christoper-v0-axariqrv8xz01.jpg?width=640&crop=smart&auto=webp&s=0b1fca4f6f6a4d564f9cab456e16e2cdf42c6b3a",
    createdAt: new Date("2026-03-20T12:00:00Z"),
    likes: 67000,
    comments: 540,
  },
  {
    id: "9",
    author: {
      name: "Máquina de Mistérios News",
      username: "mystery_inc_official",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_k_k_k_k",
    },
    content: "🐕 URGENTE: SCOOBY-DOO É FLAGRADO EM DIETA DETOX!\n\nOnde foi parar aquele apetite voraz? O cachorro mais famoso da Mystery Inc. foi visto comendo apenas alface e ração integral. \n\nSalsicha está inconsolável: 'Ele não quer mais dividir meu sanduíche, cara. Ele diz que o glúten está afetando o faro dele'. Rumores dizem que Fred e Velma obrigaram o cão a entrar em forma após ele ficar entalado em uma passagem secreta. O Scooby-Lanche agora é feito de chia. É o fim de uma era! #ScoobyDetox #CadeOSanduiche",
    image: "https://tm.ibxk.com.br/2024/04/17/17103700370051.jpg",
    createdAt: new Date("2026-03-15T18:30:00Z"),
    likes: 25600,
    comments: 1100,
  },
  {
    id: "10",
    author: {
      name: "Capsule Corp. Network",
      username: "capsule_corp_news",
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_z_z",
    },
    content: "🥗 EXPOSED: GOKU É FLAGRADO COMENDO BROCOLIS!\n\nO Príncipe dos Saiyajins não perdoou! Vegeta postou uma foto de Son Goku recusando uma coxa de dinossauro para comer uma salada de brócolis cozido no vapor. \n\n'Eu sempre soube que esse Kakarotto estava ficando mole', escreveu Vegeta na legenda. Chi-Chi, por outro lado, comemorou: 'Finalmente ele entendeu que o colesterol de um Super Saiyajin também sobe!'. A comunidade guerreira está em choque com essa mudança radical de dieta. #GokuSaudavel #VegetaTrolador",
    image: "https://tm.ibxk.com.br/2022/09/20/20115506454129.jpg?ims=400x0/filters:quality(70)",
    createdAt: new Date("2026-03-10T09:00:00Z"),
    likes: 110000,
    comments: 8900,
  }
];
